Check for git tag using try catch

diff --git a/.github/workflows/android-build-verify.yml b/.github/workflows/android-build-verify.yml
--- a/.github/workflows/android-build-verify.yml
+++ b/.github/workflows/android-build-verify.yml
@@ -96,13 +96,18 @@ jobs:
 
       - name: Check for git tag
         run: |
-          LATEST_COMMIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
-          if [[ -z "$LATEST_COMMIT_TAG" ]]; then
-            echo "No Git tag found for latest commit"
-          exit 1
-          else
+          try {
+            LATEST_COMMIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
+
+            if [[ -z "$LATEST_COMMIT_TAG" ]]; then
+              echo "No Git tag found for latest commit"
+              exit 1
+            fi
             echo "Git tag for latest commit: $LATEST_COMMIT_TAG"
-          fi
+          } catch {
+            echo "Error occurred while retrieving Git tag"
+            exit 1
+          }
 
       # - name: Run Build
       #   run: | 
