Add sonar check to workflow

diff --git a/.github/workflows/android-internal-build.yml b/.github/workflows/android-internal-build.yml
--- a/.github/workflows/android-internal-build.yml
+++ b/.github/workflows/android-internal-build.yml
@@ -41,84 +41,123 @@ jobs:
       - uses: actions/setup-node@v3
         with:
           node-version: '16.x'
-      
-      - name: Cache local npm repository
-        uses: actions/cache@v3.0.11
+          
+      - uses: actions/checkout@v3.1.0
         with:
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          path: ~/.npm
-
-      - name: Cache local gradle repository
-        uses: actions/cache@v3.0.11
-        with:
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          path: |
-            ~/.gradle/caches
-            ~/.gradle/wrapper
+          fetch-depth: 0
 
       - name: Install npm dependencies
         run: |
           npm ci
 
-      - name: Create .env.local file
-        run: |
-          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties
-
-      - name: Setup branch and env
-        run: |
-          # Strip git ref prefix from version
-          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
-          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   
-
-      - name: Setup branch and GPG public key
-        run: |
-          # Strip git ref prefix from version
-          echo ${{ env.BRANCH_NAME }}
-          echo ${{ env.GPG_TTY }}
-
-          sudo apt-get --yes install gnupg2
-          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
-          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg
-
-      - name: Setup Firebase
-        run: |
-          cd android
-          if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg2 --quiet --batch --passphrase=$FIREBASE_SECRET --pinentry-mode loopback --decrypt --output app/google-services.json app/mosip-google-services.json.gpg;fi
+      - uses: sonarsource/sonarqube-scan-action@master
+        with:
+          args:
+            -Dsonar.organization=${{ secrets.ORG_KEY }}
         env:
-          FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: https://sonarcloud.io
+          SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
 
-      - name: Generate keystore
+      - name: Check for critical bugs in SonarQube
+        env:
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          echo "$ANDROID_KEYSTORE_FILE" > release.keystore.b64
-          base64 -d -i release.keystore.b64 > android/app/release.keystore
-        env:
-          ANDROID_KEYSTORE_FILE: ${{ secrets.INJI_ANDROID_RELEASE_KEYSTORE }}
+          issues=$(curl -s -H "Authorization: Basic $(echo -n $SONAR_TOKEN:)" "${SONAR_HOST_URL}/api/issues/search?componentKeys=mimoto&resolved=false") 
 
-      - name: Export variables for keystore
+          critical_bugs_unresolved=$(echo "$issues" | jq '.issues | map(select(.type == "BUG" and .severity == "CRITICAL" and .status == "OPEN")) | length')
+
+          if [ "$critical_bugs_unresolved" -gt 0 ]; then
+            echo "Critical bugs in unresolved status found. Failing the pipeline."
+            exit 1
+          else
+            echo "No critical bugs in unresolved status. Pipeline continues."
+          fi
+
+      - uses: sonarsource/sonarqube-quality-gate-action@master
+        timeout-minutes: 3
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+
+      # - name: Cache local npm repository
+      #   uses: actions/cache@v3.0.11
+      #   with:
+      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+      #     path: ~/.npm
+
+      # - name: Cache local gradle repository
+      #   uses: actions/cache@v3.0.11
+      #   with:
+      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+      #     path: |
+      #       ~/.gradle/caches
+      #       ~/.gradle/wrapper
+
+      - name: Install npm dependencies
         run: |
-          cd android/app
-          export RELEASE_KEYSTORE_ALIAS=androidreleasekey
-          export RELEASE_KEYSTORE_PASSWORD=$RELEASE_KEYSTORE_PASSWORD
-        env: 
-          RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'
+          npm ci
 
-      - name: Create Google Play Config file
-        run : |
-          cd android
-          echo "$INJI_ANDROID_PLAY_STORE_CONFIG_JSON" > play_config.json.b64
-          base64 -d -i play_config.json.b64 > play_config.json
-        env:
-          INJI_ANDROID_PLAY_STORE_CONFIG_JSON: ${{ secrets.INJI_ANDROID_PLAY_STORE_CONFIG_JSON }}
+      # - name: Create .env.local file
+      #   run: |
+      #     echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties
 
-      - name: Run Build
-        run: | 
-          cd android/scripts
-          ./internal-build.sh
-        env:
-          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
-          APPLICATION_THEME: ${{ github.event.inputs.theme }} 
-          RELEASE_KEYSTORE_ALIAS: androidreleasekey
-          RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'
-          SLACK_URL: '${{ secrets.SLACK_WEBHOOK_DEVOPS }}'
-          PLAY_CONSOLE_RELEASE_DESCRIPTION: ${{ github.event.inputs.buildDescription }}
-          CREDENTIAL_REGISTRY_EDIT: ${{ github.event.inputs.registry_edit }}
+      # - name: Setup branch and env
+      #   run: |
+      #     # Strip git ref prefix from version
+      #     echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
+      #     echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   
+
+      # - name: Setup branch and GPG public key
+      #   run: |
+      #     # Strip git ref prefix from version
+      #     echo ${{ env.BRANCH_NAME }}
+      #     echo ${{ env.GPG_TTY }}
+
+      #     sudo apt-get --yes install gnupg2
+      #     gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
+      #     gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg
+
+      # - name: Setup Firebase
+      #   run: |
+      #     cd android
+      #     if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg2 --quiet --batch --passphrase=$FIREBASE_SECRET --pinentry-mode loopback --decrypt --output app/google-services.json app/mosip-google-services.json.gpg;fi
+      #   env:
+      #     FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}
+
+      # - name: Generate keystore
+      #   run: |
+      #     echo "$ANDROID_KEYSTORE_FILE" > release.keystore.b64
+      #     base64 -d -i release.keystore.b64 > android/app/release.keystore
+      #   env:
+      #     ANDROID_KEYSTORE_FILE: ${{ secrets.INJI_ANDROID_RELEASE_KEYSTORE }}
+
+      # - name: Export variables for keystore
+      #   run: |
+      #     cd android/app
+      #     export RELEASE_KEYSTORE_ALIAS=androidreleasekey
+      #     export RELEASE_KEYSTORE_PASSWORD=$RELEASE_KEYSTORE_PASSWORD
+      #   env: 
+      #     RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'
+
+      # - name: Create Google Play Config file
+      #   run : |
+      #     cd android
+      #     echo "$INJI_ANDROID_PLAY_STORE_CONFIG_JSON" > play_config.json.b64
+      #     base64 -d -i play_config.json.b64 > play_config.json
+      #   env:
+      #     INJI_ANDROID_PLAY_STORE_CONFIG_JSON: ${{ secrets.INJI_ANDROID_PLAY_STORE_CONFIG_JSON }}
+
+      # - name: Run Build
+      #   run: | 
+      #     cd android/scripts
+      #     ./internal-build.sh
+      #   env:
+      #     MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
+      #     APPLICATION_THEME: ${{ github.event.inputs.theme }} 
+      #     RELEASE_KEYSTORE_ALIAS: androidreleasekey
+      #     RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'
+      #     SLACK_URL: '${{ secrets.SLACK_WEBHOOK_DEVOPS }}'
+      #     PLAY_CONSOLE_RELEASE_DESCRIPTION: ${{ github.event.inputs.buildDescription }}
+      #     CREDENTIAL_REGISTRY_EDIT: ${{ github.event.inputs.registry_edit }}
