[INJI-597] add sonar check in push trigger & internal build
Co-authored-by:  PuBHARGAVI <46226958+PuBHARGAVI@users.noreply.github.com>
Signed-off-by: KiruthikaJeyashankar <81218987+KiruthikaJeyashankar@users.noreply.github.com>

diff --git a/.github/workflows/internal-build.yml b/.github/workflows/internal-build.yml
--- a/.github/workflows/internal-build.yml
+++ b/.github/workflows/internal-build.yml
@@ -170,6 +170,32 @@ jobs:
     with:
       SERVICE_LOCATION: '.'
     secrets:
+      BUILD_SCRIPT: 'npm run build'
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
       SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK }}'
+  
+  check-sonar-critical-issues:
+    needs: sonar-check
+    name: Check critical issues in sonar analysis
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install jq
+        run: sudo apt-get -y install jq
+      - name: Check for critical bugs
+        run: |
+          SONAR_HOST_URL=https://sonarcloud.io
+          SONAR_PROJECT_KEY=mosip_inji
+
+          response=$(curl -s "${SONAR_HOST_URL}/api/issues/search?componentKeys=${SONAR_PROJECT_KEY}&severities=CRITICAL&statuses=OPEN")
+          echo "The response is $response"
+
+          issues_count=$(echo "$response" | jq '.issues | length')
+          echo "The number of issues $issues_count"
+
+          if [ "$issues_count" -eq 0 ]; then
+              echo "No critical issues found."
+          else
+              echo "Critical issues found. Failing the pipeline"
+              exit 1
+          fi
diff --git a/.github/workflows/push-triggers.yml b/.github/workflows/push-triggers.yml
--- a/.github/workflows/push-triggers.yml
+++ b/.github/workflows/push-triggers.yml
@@ -7,6 +7,7 @@ on:
     - develop
     - qa-develop
     - 'release-**'
+    - inji-sonar-qube-android
   release:
     types: [published]
   pull_request:
@@ -16,6 +17,7 @@ on:
     - develop
     - qa-develop
     - 'release-**'
+    - inji-sonar-qube-android
 
 jobs:
   build-android:
@@ -38,13 +40,56 @@ jobs:
       IOS_SERVICE_LOCATION: 'ios'
       SCRIPT_NAME: "fastlane ios_app_build"
 
-  # sonar-check:
-  #   if: ${{ github.event_name != 'pull_request' }}
-  #   uses: mosip/kattu/.github/workflows/gradlew-sonar-analysis.yml@master
-  #   with:
-  #     SERVICE_LOCATION: '.'
-  #     ANDROID_LOCATION: 'android'
-  #   secrets:
-  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-  #     SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
-  #     SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK }}'
+  sonar-check-on-pr:
+    name: Sonar check
+    if: ${{ github.event_name == 'pull_request' }}
+    uses: tw-mosip/kattu/.github/workflows/npm-sonar-analysis.yml@inji-add-release-keystore-step-for-sonar
+    with:
+      SERVICE_LOCATION: '.'
+      SONAR_ARGS: '-Dsonar.branch.name=${{ github.head_ref }} -Dsonar.branch.target=${{ github.base_ref }}'
+      BUILD_SCRIPT: 'npm run build'
+    secrets:
+      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
+      SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK }}'
+  
+  sonar-check-on-push:
+    name: Sonar check
+    if: ${{ github.event_name != 'pull_request' }}
+    needs: [build-android, build-ios]
+    uses: tw-mosip/kattu/.github/workflows/npm-sonar-analysis.yml@inji-add-release-keystore-step-for-sonar
+    with:
+      SERVICE_LOCATION: '.'
+      BUILD_SCRIPT: 'npm run build'
+    secrets:
+      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
+      SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK }}'
+
+  check-sonar-critical-issues:
+    needs: [sonar-check-on-pr, sonar-check-on-push]
+    if: |
+      always() && 
+      (needs.sonar-check-on-pr.result == 'success' || needs.sonar-check-on-push.result == 'success')
+    name: Check critical issues in sonar analysis
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install jq
+        run: sudo apt-get -y install jq
+      - name: Check for critical bugs
+        run: |
+          SONAR_HOST_URL=https://sonarcloud.io
+          SONAR_PROJECT_KEY=mosip_inji
+
+          response=$(curl -s "${SONAR_HOST_URL}/api/issues/search?componentKeys=${SONAR_PROJECT_KEY}&severities=CRITICAL&statuses=OPEN")
+          echo "The response is $response"
+
+          issues_count=$(echo "$response" | jq '.issues | length')
+          echo "The number of issues $issues_count"
+
+          if [ "$issues_count" -eq 0 ]; then
+              echo "No critical issues found."
+          else
+              echo "Critical issues found. Failing the pipeline"
+              exit 1
+          fi
