update iosbuild.yml

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -3,8 +3,6 @@ on:
   push:
     branches:
       - develop
-      - ci-publish
-      - inji-244
 jobs:
   build:
     name: Build
@@ -18,8 +16,7 @@ jobs:
           npm ci
       - uses: sonarsource/sonarqube-scan-action@master
         with:
-          args:
-            -Dsonar.organization=${{ secrets.ORG_KEY }}
+          args: -Dsonar.organization=${{ secrets.ORG_KEY }}
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: https://sonarcloud.io
@@ -30,24 +27,24 @@ jobs:
 
       - name: Check for critical bugs
         run: |
-              # Fetch SonarQube issues using the API
-              SONAR_HOST_URL=https://sonarcloud.io
-              SONAR_PROJECT_KEY=mosip_inji
+          # Fetch SonarQube issues using the API
+          SONAR_HOST_URL=https://sonarcloud.io
+          SONAR_PROJECT_KEY=mosip_inji
 
-              # Fetch issues using the SonarQube API
-              response=$(curl -s "${SONAR_HOST_URL}/api/issues/search?componentKeys=${SONAR_PROJECT_KEY}&severities=CRITICAL&statuses=OPEN") 
-              echo "The response is $response" 
+          # Fetch issues using the SonarQube API
+          response=$(curl -s "${SONAR_HOST_URL}/api/issues/search?componentKeys=${SONAR_PROJECT_KEY}&severities=CRITICAL&statuses=OPEN") 
+          echo "The response is $response" 
 
-              # Extract the value of "issues" field
-              issues_count=$(echo "$response" | jq '.issues | length')
-              echo "The number of issues $issues_count"
+          # Extract the value of "issues" field
+          issues_count=$(echo "$response" | jq '.issues | length')
+          echo "The number of issues $issues_count"
 
-              if [ "$issues_count" -eq 0 ]; then
-                echo "No critical issues found."
-              else
-                echo "Critical issues found. Failing the pipeline"
-                exit 1
-              fi
+          if [ "$issues_count" -eq 0 ]; then
+            echo "No critical issues found."
+          else
+            echo "Critical issues found. Failing the pipeline"
+            exit 1
+          fi
 
       # If you wish to fail your job when the Quality Gate is red, uncomment the
       # following lines. This would typically be used to fail a deployment.
